#!/bin/bash -e
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ "$OPENSHIFT_APP_DNS" == "$OPENSHIFT_GEAR_DNS" ]
then
  if [ -f "${OPENSHIFT_DATA_DIR}local.xml" ]; then
    mkdir -p ${OPENSHIFT_REPO_DIR}.openshift/magento
    cp ${OPENSHIFT_DATA_DIR}local.xml ${OPENSHIFT_REPO_DIR}.openshift/magento/local.xml
  fi

  if [ -d ${OPENSHIFT_DATA_DIR}media ]
  then
    mkdir -p ${OPENSHIFT_REPO_DIR}.openshift/magento
    cp -r ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}.openshift/magento/
  fi

  if [ -d ${OPENSHIFT_DATA_DIR}skin ]
  then
    mkdir -p ${OPENSHIFT_REPO_DIR}.openshift/magento
    cp -r ${OPENSHIFT_DATA_DIR}skin ${OPENSHIFT_REPO_DIR}.openshift/magento/
  fi
fi
